# Generated by Django 4.2.30 on 2026-05-28 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('offered_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_exchange_requests', to='items.clothingitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_exchange_requests', to='items.clothingitem')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange Request',
                'verbose_name_plural': 'Exchange Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('final_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20)),
                ('requester_feedback', models.TextField(blank=True)),
                ('owner_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='exchanges.exchangerequest')),
            ],
            options={
                'verbose_name': 'Exchange History',
                'verbose_name_plural': 'Exchange Histories',
            },
        ),
        migrations.CreateModel(
            name='ExchangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='exchanges.exchangerequest')),
            ],
            options={
                'verbose_name': 'Exchange Event',
                'verbose_name_plural': 'Exchange Events',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='exchangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('requester', 'requested_item', 'offered_item'), name='unique_pending_exchange_request'),
        ),
    ]
