# Generated by Django 4.2.30 on 2026-05-31

import apps.items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.items.models.item_image_upload_path, validators=[apps.items.models.validate_image_size]),
        ),
    ]
